# ECS
[services.ecs]
restart-commands = ["/usr/bin/ecs-settings-applier", "/bin/systemctl try-reload-or-restart ecs.service"]
configuration-files = ["ecs-config"]

[configuration-files.ecs-config]
path = "/etc/ecs/ecs.config"
template-path = "/usr/share/templates/ecs.config"

[metadata.settings.ecs]
affected-services = ["ecs"]

[settings.ecs]
allow-privileged-containers = false
image-pull-behavior = "default"
logging-drivers = ["json-file", "awslogs", "none"]
loglevel = "info"

# Metrics
[settings.metrics]
service-checks = ["apiserver", "chronyd", "containerd", "host-containerd", "docker", "ecs"]

# Network
[metadata.settings.network]
affected-services = ["containerd", "docker", "ecs", "host-containerd", "host-containers"]

# Image registry credentials
[metadata.settings.container-registry.credentials]
affected-services = ["ecs", "host-containers", "bootstrap-containers"]
