[package]
name = "makedumpfile"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/makedumpfile/makedumpfile/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/makedumpfile/makedumpfile/archive/1.7.2/makedumpfile-1.7.2.tar.gz"
sha512 = "324e303dd5f507703f66e2bd5dc9d24f9f50ba797be70c05702008ba77078f61ffcc884796ddf9ab737de1d124c3a9d881ab5ce4f3f459690ec00055af25ea9e"

[build-dependencies]
glibc = { path = "../glibc" }
libelf = { path = "../libelf" }
libz = { path = "../libz" }
libbzip2 = { path = "../libbzip2" }
