version = {{version}}

[bond0]
kind = "bond"
mode = "active-backup"
interfaces = ["f8:74:a4:d5:32:64"]
dhcp4 = true

[bond0.monitoring]
miimon-frequency-ms = 100
miimon-updelay-ms = 200
miimon-downdelay-ms = 200
