[workspace]
members = [
    "api/apiserver",
    "api/apiclient",
    "api/bootstrap-containers",
    "api/bork",
    "api/certdog",
    "api/corndog",
    "api/datastore",
    "api/early-boot-config",
    "api/ecs-settings-applier",
    "api/netdog",
    "api/sundog",
    "api/schnauzer",
    "api/pluto",
    "api/host-containers",
    "api/static-pods",
    "api/storewolf",
    "api/thar-be-settings",
    "api/thar-be-updates",
    "api/settings-committer",
    "api/migration/migrator",
    "api/migration/migration-helpers",
    "api/shibaken",
    "api/prairiedog",

    # "api/migration/migrations/vX.Y.Z/..."
    # (all previous migrations archived; add new ones after this line)
    "api/migration/migrations/v1.12.0/k8s-private-pki-path",
    "api/migration/migrations/v1.12.0/add-k8s-autoscaling-warm-pool-setting",
    "api/migration/migrations/v1.12.0/add-k8s-autoscaling-warm-pool-setting-metadata",
    "api/migration/migrations/v1.12.0/oci-defaults-setting",
    "api/migration/migrations/v1.12.0/oci-defaults-setting-metadata",
    "api/migration/migrations/v1.12.0/aws-admin-container-v0-9-4",
    "api/migration/migrations/v1.12.0/public-admin-container-v0-9-4",
    "api/migration/migrations/v1.12.0/aws-control-container-v0-7-0",
    "api/migration/migrations/v1.12.0/public-control-container-v0-7-0",
    "api/migration/migrations/v1.13.0/k8s-registry",
    "api/migration/migrations/v1.13.0/aws-admin-container-v0-10-0",
    "api/migration/migrations/v1.13.0/public-admin-container-v0-10-0",
    "api/migration/migrations/v1.13.0/aws-control-container-v0-7-1",
    "api/migration/migrations/v1.13.0/public-control-container-v0-7-1",
    "api/migration/migrations/v1.13.1/aws-profile-cred-provider",
    "api/migration/migrations/v1.14.0/kubernetes-gc-percent-type-change",

    "bottlerocket-release",

    "bottlerocket-variant",

    "imdsclient",

    "driverdog",

    "generate-readme",

    "ghostdog",

    "metricdog",

    "cfsignal",

    "logdog",

    "models",

    "parse-datetime",

    "retry-read",

    "updater/block-party",
    "updater/signpost",
    "updater/update_metadata",
    "updater/updog",

    "constants",

    "shimpei"
]

[profile.release]
debug = true
