[package]
name = "nvidia-k8s-device-plugin"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/NVIDIA/k8s-device-plugin/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/NVIDIA/k8s-device-plugin/archive/v0.13.0/v0.13.0.tar.gz"
path = "k8s-device-plugin-0.13.0.tar.gz"
sha512 = "c6b29ed4c13e06ec798727364476cb0febc6afd97cdfe4daf89c8f6f91119c26b8627553431105f5e13fdd7a7ce5cd38d4b6567f756f660e99655ab2b6fa2a32"

[build-dependencies]
glibc = { path = "../glibc" }
