blank_issues_enabled: false
contact_links:
  - name: Bottlerocket Community Form
    url: https://github.com/bottlerocket-os/bottlerocket/discussions
    about: Please ask and answer questions here.
    label: foobar