name: Documentation
labels: ["status/needs-triage", "type/documentation"]
description: Let us know about a problem with Bottlerocket's documentation.
body:
  - type: markdown
    attributes:
      value: |
        This bug report form is for docuemntation issues related to Bottlerocket.
  - type: dropdown
    id: doctype
    attributes:
      label: This issue is related to documentation concerning...
      options:
        - Using Bottlerocket
        - Developing Bottlerocket
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL of documentation
      description: The location of the documentation you have an issue with
      placeholder: https://github.com/bottlerocket-os/bottlerocket/blob/develop/README.md
    validations:
      required: false
  - type: textarea
    id: expect
    attributes:
      label: I expected to find documented
      render: bash
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What was actually documented
      render: bash
    validations:
      required: true


