name: Feature Request
labels: ["status/needs-triage", "type/enhancement"]
description: Let us know about a problem in the build process of Bottlerocket
body:
  - type: markdown
    attributes:
      value: |
        This form is for **feature request** to Bottlerocket. 
        
        A few tips before submitting a new issue:
        - Search for similar features requests, including in [closed issues](https://github.com/bottlerocket-os/bottlerocket/issues?q=is%3Aissue+is%3Aclosed),
        - Search for similar features already on the [Bottlerocket roadmap](https://github.com/bottlerocket-os/bottlerocket/blob/develop/ROADMAP.md).
  - type: textarea
    id: like
    attributes:
      label: What I'd like
      render: bash
    validations:
      required: true
  - type: textarea
    id: like
    attributes:
      label: Any alternatives you've considered
      render: bash
    validations:
      required: true
  - type: checkboxes
    id: collaborate
    attributes:
      label: How would you like this feature to be developed?
      options:
        - label: I'm willing to fully contribute the code for this feature
        - label: I'm willing to collaborate with the team for this feature
        - label: I cannot contribute the code for this feature
    validations:
      required: true

