[package]
name = "libglib"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://download.gnome.org/sources/glib"

[[package.metadata.build-package.external-files]]
url = "https://download.gnome.org/sources/glib/2.75/glib-2.75.3.tar.xz"
sha512 = "44aa53d0dae69e50c8d5d9adb7c90034c4c2ab5db3c74106c91bfdbdca41bc5523b32b16c33bc65b3c6bf0037bdecb344b80e9708930bde54ac7c618c34ea5a8"

[build-dependencies]
glibc = { path = "../glibc" }
libffi = { path = "../libffi" }
libpcre = { path = "../libpcre" }
libselinux = { path = "../libselinux" }
libz = { path = "../libz" }
util-linux = { path = "../util-linux" }
