[package]
name = "libelf"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://sourceware.org/elfutils/ftp/"

[[package.metadata.build-package.external-files]]
url = "https://sourceware.org/elfutils/ftp/0.188/elfutils-0.188.tar.bz2"
sha512 = "585551b2d937d19d1becfc2f28935db1dd1a3d25571a62f322b70ac8da98c1a741a55d070327705df6c3e2ee026652e0b9a3c733b050a0b0ec5f2fc75d5b74b5"

[build-dependencies]
glibc = { path = "../glibc" }
libz = { path = "../libz" }
