[package]
name = "retry-read"
version = "0.1.0"
authors = ["Tom Kirchner <tjk@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[build-dependencies]
generate-readme = { version = "0.1", path = "../generate-readme" }
