[package]
name = "kernel-5_10"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[package.metadata.build-package]
variant-sensitive = "platform"
package-name = "kernel-5.10"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/bfdedd54405ee75070fa9b53342399680e3145e362f41deb1276de2082625061/kernel-5.10.173-154.642.amzn2.src.rpm"
sha512 = "b98f97a00dfbec2ba6681faa326782bbe02c8a57758890076f71bb07a149d6dee3dba1237c07fb195c6a65956bee572f0d8757898375f437244eec7e69938e0b"

[build-dependencies]
microcode = { path = "../microcode" }
