[package]
name = "tcpdump"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "http://www.tcpdump.org/release"

[[package.metadata.build-package.external-files]]
url = "http://www.tcpdump.org/release/tcpdump-4.99.3.tar.gz"
sha512 = "e1442e923d89f367cfe403dc460d0d46e19a241470d56b30b7a411bedd8d21a78c428f20ffe725cbb4fa5068f7dcc5c93d206e1a8d53feb9bccc6f0cda8bf0f9"

[build-dependencies]
glibc = { path = "../glibc" }
libpcap = { path = "../libpcap" }
